DROP TABLE IF EXISTS example.CUSTOMERS;
DROP TABLE IF EXISTS example.ITEMS;

CREATE TABLE example.CUSTOMERS(
  ID VARCHAR(36) PRIMARY KEY,
  FIRST_NAME VARCHAR(256) NOT NULL,
  LAST_NAME VARCHAR(256) NOT NULL,
  ADDRESS VARCHAR(1024) NOT NULL
);

CREATE TABLE example.ITEMS(
  ID VARCHAR(36) PRIMARY KEY,
  ITEM_NAME VARCHAR(256) NOT NULL,
  DESCRIPTION VARCHAR(256) NOT NULL
);